name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-ci:
    uses: ./.github/workflows/rust-ci.yml
    with:
      rust-version: 'stable'
      features: 'all'

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [rust-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build release binary
      run: cargo build --release

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fukura-${{ runner.os }}-${{ github.sha }}
        path: target/release/fukura
